apiVersion: v1
kind: Service
metadata:
  name: vision-webapp
  labels:
    app: vision
    role: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: "http-server"
  selector:
    app: vision
    role: frontend

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vision-webapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: vision
        role: frontend
    spec:
      containers:
      - name: vision-webapp
        image: gcr.io/$GCLOUD_PROJECT/awwvision-webapp
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: redis-master
        - name: GCLOUD_PROJECT
          value: $GCLOUD_PROJECT
        ports:
        - name: http-server
          containerPort: 8080

---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vision-worker
  labels:
    app: vision
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: vision
        tier: worker
    spec:
      containers:
      - name: vision-worker
        image: gcr.io/visionproject-266515/vision-webapp
        imagePullPolicy: Always
        env:
        - name: PROCESSES
          value: worker